# Generated by Django 5.0.6 on 2024-06-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comic_cost_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='comics',
            new_name='comic_ids',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
